"""
File: Rig.py
Description: Module to define the Rig class and Methods part of
the Into the Grid OOP Basic Programming assessment COMP 1048 2025P6.
Author: Jorge Ortega
ID: 110482203
Username: ortjy007
This is my own work as defined by the University's Academic Misconduct Policy.
"""

from Asset import Asset
from random import randint
import sys
import os

class Rig:
    """
    Rig class representing computers.
    Class level attribute:
    -CONDITION

    Instance level attributes:
    -name: str
    -damage: int
    -broken: bool
    -condition: int
    -storage: list (starts with the following Assets:
    data_spikes x2, encrypted_drive)

    Methods w/decorators:
    +name @property getter + setter
    +damage @property getter + setter
    +broken @property getter + setter
    +condition @property getter + setter
    +storage @property getter + setter

    Rig class methods:
    Storing_assets: validated list storing digital assets.
    Releasing_asset: releasing non encrypted asset after validation.
    Releasing_all_assets: releasing all non encrypted assets from storage.
    Upgrading: Validating asset and upgrading the Rig's condition
    to reduce damage and increase storage.
    Taking_hits: Validating asset and increasing damage levels per hit.
    Repairing: Validating assent and repairing damage generated by hits.
    Generate_asset: Generate a random asset from the Asset module.

    Static method:
    Consume_asset: Remove asset from storage as consumed
    """
    # Condition levels for all Rigs
    CONDITION = {2: 'Broken', 1.5: 'Holding on', 1: 'A bit hammered',
                 .5: 'Just a scratch', 0: 'Pristine', -.5: 'Almost mint',
                 -1: 'Robust', -1.5: 'Armored', -2: 'Awsome'}

    def __init__(self, name: str):

        # Using redirecting the standard output stream while the assets
        # are created during initialization
        or_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')

        self.name = name
        self.damage = 0
        self.broken = False
        self.condition = 0
        self.storage = [Asset('data_spike'), Asset('data_spike'),
                        Asset('removable_drive')]

        # Standard output stream restored
        sys.stdout.close()
        sys.stdout = or_stdout

    def __str__(self):
        """
        Values and format as requested in the
        specification.
        :return: str
        """
        # Extracting the names of the assets into a temp list
        tmp_list = [item.name for item in self.__storage]

        # The negative number in upgrade is because the value of
        # the upgrades is negative to offset the positive value
        # of the damage as specified in the brief.
        return (f'\nRig: {self.__name}\n'
                f'Condition: {Rig.CONDITION[self.__condition]}\n'
                f'Upgrade level: {self.__condition * -1}\n'
                f'Stored assets: {*tmp_list,}\n\n')

    @property
    def name(self) -> str:
        """Name property"""
        return self.__name

    @name.setter
    def name(self, s_name: str) -> None:
        self.__name = s_name

    @property
    def damage(self) -> int:
        """damage property"""
        return self.__damage

    @damage.setter
    def damage(self, s_damage: int) -> None:
        self.__damage = s_damage

    @property
    def broken(self) -> bool:
        """broken property"""
        return self.__broken

    @broken.setter
    def broken(self, s_broken: bool) -> None:
        self.__broken = s_broken

    @property
    def condition(self) -> int:
        """condition property"""
        return self.__condition

    @condition.setter
    def condition(self, s_condition: int) -> None:
        self.__condition = s_condition

    @property
    def storage(self) -> list:
        """condition property"""
        return self.__storage

    @storage.setter
    def storage(self, s_storage: list) -> None:
        self.__storage = s_storage

    # Class Methods
    def storing_assets(self, asset: Asset) -> None:
        """
        Storing assets in the Rig's storage after validation
        and printing the revised contents of storage w/ decryption
        status.
        :param asset: Asset
        :return:
        """
        if isinstance(asset, Asset) and asset.encrypted != True:
            self.__storage.append(asset)

            # Extracting the names and encryption status of the assets
            # into a temp list
            tmp_list = []
            group_s = 3

            for item in self.__storage:
                tmp_list.append('A')
                tmp_list.append(item.name)
                tmp_list.append('has been stored.')

            # printing in legible groups
            for i in range(0, len(tmp_list), group_s):
                group = tmp_list[i:i + group_s]
            print(*group)
        else:
            print('Only decrypted valid assets can be saved')

    def releasing_asset(self, asset_name: str) -> Asset:
        """
        Releasing asset from storage if it exists and is decrypted.
        :param asset_name: str
        :return: Asset
        """
        return_asset = None

        # Validating the asset name against the valid assets, check that
        # is not encrypted, copying it to a holding variable and deleting
        # from the Rig's storage. Return the asset on the holding variable.
        if asset_name in Asset.ASSET_NAMES:
            for item in self.__storage:
                if item.name == asset_name and item.encrypted != True:
                    return_asset = item
            if isinstance(return_asset, Asset):
                self.__storage.remove(return_asset)
                print(f'{asset_name} released from storage.')
            else:
                print(f'No decrypted {asset_name} in storage.')
        else:
            print(f'Need a valid asset name.')
        return return_asset

    def releasing_all_assets(self) -> list:
        """
        Releasing all assets from storage if they are decrypted.
        :return: list
        """
        # Creating a sync list of items in storage, identifying index
        # saving the asset in a temporary variable to be returned and
        # deleting from the storage list

        return_list = []
        for item in self.__storage:
            if not item.encrypted:
                return_list.append(item.name)
                self.__storage.remove(item)

        # Creating a list of name of the remaining items in storage
        tmp_list = [item.name for item in self.__storage]

        print(f'The following assets have been released', return_list)
        print(f'Remaining encrypted assets remain:', tmp_list)
        return return_list

    def upgrading(self, asset: Asset) -> None:
        """
        Upgrading Rig method validating the asset as a 'hardware patch'
        and upgrading one unit at the time to maximum of 2 (neg).
        Printing Rig condition after upgrade.
        :param asset: 'hardware patch'
        :return:
        """
        if isinstance(asset, Asset) and asset.name == 'hardware_patch':
            self.__condition -= 1
            if self.__condition < -2:
                self.__condition = -2
            print(f'{self.__name} has been upgraded to '
                  f'{Rig.CONDITION[self.__condition]}.')
        else:
            print('Upgrade can only be done using a hardware_patch.\n')

    def taking_hits(self) -> None:
        """
        Taking hits method reducing the rigs condition while increasing
        the damage.
        .5 damage if the rig's condition is awsome or better
        1 if the rig's condition is pristine or worse
        if maximums or minimums are exceeded they reset to the max values
        Printing Rig condition after damage.
        :return:
        """
        # Starting with a better rig
        if self.__condition <= 0:
            self.__damage += .5
            self.__condition +=.5

            # Keeping damage between boundaries
            if self.__damage > 2:
                self.__damage = 2
            if self.__condition > 2:
                self.__condition = 2

        # Continue with an average rig
        elif self.__condition >0:
            self.damage += 1
            self.__condition += 1

            # Keeping damage between boundaries
            if self.__damage > 2:
                self.__damage = 2
            if self.__condition > 2:
                self.__condition = 2

        print(f'{self.__name} has taken a hit and its condition is '
              f'{Rig.CONDITION[self.__condition]}.')

    def repairing(self, asset: Asset) -> None:
        """
        Repairing a Rig method, validating for damage status (< 0) and
        crypto_token asset, damage level set to 0 and broken status
        reset to False.
        :param asset: 'crypto_token'
        :return: None
        """
        if self.__condition <= 0:
            print(f'{self.__name} is not damaged, no repairs done.')
        elif isinstance(asset, Asset) and asset.name == 'crypto_token':
            self.__damage = 0
            self.__broken = False
            self.__condition = 0
            print(f'{self.__name} has been repaired and it is Pristine with '
                  f'0 damage.')
        else:
            print('A valid crypto_token asset is needed, no repairs done.')

    def generate_asset(self) -> Asset:
        """
        Static method to generate a random asset from the Asset types valid
        in the Asset module.
        :return: new_asset: Asset
        """
        select = randint(0, len(Asset.ASSET_NAMES) - 1)
        new_asset = Asset(Asset.ASSET_NAMES[select])
        print(f'\nA {new_asset.name} has been randomly created.')
        return new_asset
